        <!--RESUME DATA-->
        <div class="hide">
            <section class="block" id="alma">
                <h1 class="resume-title left">Developer & Designer</h1>
                 <p class="resume-location right">New York, NY</p>
            	<div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.alma33nyc.com" target="_blank"><img height="74" width="150" alt="Alma 33 Logo" src="/img/logo_alma33.gif"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Increased restaurant's reputation and brand through site design and enhancment.</li>
                    <li>Using micro data boosts the search engine optimization (SEO) and page rank.</li>
                    <li>HTML5 site allowing for iPhone and iPad compatibility as well as use of CSS3 and semantic markup</li>
                </ul>                        
            	<div class="clr"></div>
                <br>
            </section>
        </div><!-- END #alma -->
        <div class="hide">
            <section class="block" id="absolutSF">
                <h1 class="resume-title left">Developer</h1>
                 <p class="resume-location right">New York, NY</p>
            	<div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="https://www.facebook.com/ABSOLUT?sk=app_219844078040630" target="_blank"><img height="74" width="150" alt="Absolut Logo" src="/img/logo_absolutsf.gif"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Brought in by <a href="https://www.tbwachiat.com/" target="_blank">TBWA\Chiat\Day</a> to help finish off the Absolut SF Facebook application. </li>
                    <li>Using jQuery, HTML & CSS3 created a dynamic graph to show the visual data being generated by the database. </li>
                    <li>Ensured the application was cross browser & system compatible.</li>
                    <li></li>
                </ul>                        
            	<div class="clr"></div>
                <br>
            </section>
        </div><!-- END #absolutSF -->
        <div class="hide">
            <section class="block" id="royalwedding">
                <h1 class="resume-title left">Lead Developer & Designer</h1>
                 <p class="resume-location right">New York, NY</p>
            	<div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.eurorscg.com/royalwedding/default.aspx" target="_blank"><img height="26" width="122" alt="EuroRSCG Logo" src="/img/logo_eurorscg.gif"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Approached by Euro RSCG Worldwide to create a website with a waterfall effect of tweets singling out a specific hash tag ('#'). </li>
                    <li>Using .NET, CSS3, and jQuery I was able to quickly develop the site on 2 days notice.</li>
                    <li>Given some design elements to be used as a branding guideline, I incorporated new graphics that went seamlessly with Euro RSCG Worldwide design and brand guidelines.</li>
                </ul>                        
            	<div class="clr"></div>
                <br>
            </section>
        </div><!-- END #royalwedding -->
        <div class="hide">
            <section class="block" id="sithappens">
                <h1 class="resume-title left">Lead Developer & Designer</h1>
                 <p class="resume-location right">New York, NY</p>
            	<div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.sithappensny.com" target="_blank"><img height="126" width="90" alt="Sit Happens Logo" src="/img/logo_sithappensny.jpg"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Designed a simple business card website using jQuery, PHP, CSS3 and HTML.</li>
                    <li>Used jQuery for form validation as well as form hints.</li>
                    <li>Created a mailer function in PHP to send e-mails.</li>
                    <li>Using CSS3 I was able to reduce the load time and optimize the site for an enhanced user experience.</li>
                </ul>                        
            	<div class="clr"></div>
                <br>
            </section>
        </div><!-- END #sithappens -->
        <div class="hide">
            <section class="block" id="petflow">
                <h1 class="resume-title left">Lead Front End Engineer</h1>
                 <p class="resume-location right">New York, NY</p>
            	<div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.petflow.com" target="_blank"><img height="41" width="130" alt="PetFlow Logo" src="/img/logo_petflow.png"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Stabilized the current Drupal Code base for optimization and SEO.</li>
                    <li>Leading the team for a 2.0 code base utilizing Smarty Template running on the <a target="_blank" href="http://www.egloo.com" class="link">egloo</a> PHP framework</li>
                    <li>Responsible for all consumer facing design and layout for <a target="_blank" href="http://www.petflow.com" class="link">PetFlow.com</a>.</li>
                    <li>Create and designed HTML e-mails that are sent to the current client code base</li>
                    <li>Overhauled the look and functionality of the Admin panel using jQuery and CSS</li>
                    <li>Optimized the entire site reducing the home page from 6K+ lines of CSS down to 300 with similar results for the jQuery/javascript files.</li>
                </ul>                        
            	<div class="clr"></div>
                <br>
            </section>
        </div><!-- END #petflow -->
        <div class="hide">
            <section class="block" id="rocketfuel">
                <h1 class="resume-title left">Drupal Developer</h1>
                 <p class="resume-location right">New York, NY</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.rocketfuelstudios.com" target="_blank"><img height="25" width="150" alt="RocketFuel Logo" src="/img/logo_rocketfuel.png"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Assisted RocketFuel studios in completing the rebranding and launch of the new Major League Soccer league site, as well as all 16 team companion sites.</li>
                    <li>Utilizing CSS, PHP, Javascript and XHTML I helped theme pages for Drupal.</li>
                    <li>Fixed the navigation bar to allow current state, as well as the dropdown navigation.</li>
                    <li>Re-structured the homepage layout to match the approved photoshop composition.</li>
                    <li>Assisted in the re-theme of sub pages for a sidebar implementation.</li>
                    <li>Cleaned up Drupal in the back end, eliminating unnecessary panels and blocks as well as optimizing the CSS, panels and blocks.
                    </li>
                </ul>                       
             <div class="clr"></div>
                    <br>
            </section>
        </div><!-- END #rocketfuel -->
        <div class="hide">
            <section class="block" id="atari">
                <h1 class="resume-title left">Web Developer/Designer</h1>
                 <p class="resume-location right">New York, NY</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.atari.com?iframe" target="_blank"><img height="134" width="130" alt="Atari Logo" src="/img/logo_atari.png"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Coordinated with the project manager, setting deadline dates to ensure project movement and completion.</li>
                    <li>Created a custom template in Word Press to drive the 'Project Runway' Wii game site for Atari.com with heavy use of CSS and light manipulation of PHP.</li>
                    <li>Implemented Third party API's into the framework of the site, pulling in a Flickr photo gallery, Facebook connect, share functionality, as well as skinning of the Facebook Fan Box.</li>
                </ul>
                <div class="clr"></div>
                <br>
            </section>
        </div><!-- END #atari -->        
        <div class="hide">
            <section class="block" id="rockstar">
                <h1 class="resume-title left">Web Developer/Designer</h1>
                 <p class="resume-location right">New York, NY</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.rockstargames.com" target="_blank"><img height="121" width="130" alt="Rockstargames Logo" src="/img/logo_rockstar.png"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Worked on the marketing campaigns of the recently released Chinatown Wars, Episodes from Liberty City, Beaterator, Midnight Club Los Angeles, Grand Theft Auto IV, Grand Theft Auto Chinatown Wars, Bully Scholarship, Max Payne 3 and Red Dead Redemption.</li>
                    <li>Coordinated with Rockstar International to develop, produce and design all internationalized versions of the game sites.</li>
                    <li>Kept all internationalized sites synced with their US counterpart through use of .htaccess, Apache, cakePHP, HTML and CSS.</li>
                    <li>Set up the Research department with a comprehensive way of sending out e-blasts, archiving sent e-blasts, and developed new research sites as needed.</li>
                    <li>Updated sites for Rockstargames, Rockstargames studios, Rockstar Warehouse, Take2 Store, Social Club and Take2 Games.</li>
                    <li>Created a developer documentation library and made the process of pushing staging sites to live more efficient.</li>
                    <li>Designed, developed and deployed the Rockstar Propaganda e-newsletter via Lyris List Manager, using HTML.</li>
                </ul>                        
                <div class="clr"></div>
                    <br>
            </section>
        </div><!-- End #rockstar -->                        
        <div class="hide">
            <section class="block" id="beaterator">
                <h1 class="resume-title left">Web Developer/Designer</h1>
                 <p class="resume-location right">New York, NY</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.rockstargames.com/beaterator" target="_blank"><img height="50" width="150" alt="Rockstargames Beaterator Logo" src="/img/logo_beaterator.jpg"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Worked on the marketing campaign of Beaterator.</li>
                    <li>Coordinated with Rockstar International to develop, produce and design all internationalized versions of the game sites.
                     <ul>
                            <li><a href="http://www.rockstargames.com/beaterator/IT" target="_blank">Italian</a></li>
                            <li><a href="http://www.rockstargames.com/beaterator/DE" target="_blank">Deutch</a></li>
                            <li><a href="http://www.beaterator-eljuego.com" target="_blank">Espana</a></li>
                            <li><a href="http://www.beaterator-lejeu.com" target="_blank">Francias</a></li>
                        </ul>

                    </li>
                    <li>Kept all internationalized sites synced with their US counterpart through use of .htaccess, Apache, cakePHP, HTML and CSS.</li>
                    <li>Set up the Research department with a comprehensive way of sending out e-blasts, archiving sent e-blasts, and developed new research sites as needed.</li>
                </ul>                        
                <div class="clr"></div>
                    <br>
            </section>
        </div><!-- End #beaterator -->                        
        <div class="hide">
            <section class="block" id="mp3">
                <h1 class="resume-title left">Web Developer/Designer</h1>
                 <p class="resume-location right">New York, NY</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.rockstargames.com" target="_blank"><img height="37" width="150" alt="Rockstargames Max Payne 3 Logo" src="/img/logo_mp3.jpg"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Worked on the marketing campaigns of the recently released Chinatown Wars, Episodes from Liberty City, Beaterator, Midnight Club Los Angeles, Grand Theft Auto IV, Grand Theft Auto Chinatown Wars, Bully Scholarship, Max Payne 3 and Red Dead Redemption.</li>
                    <li>Coordinated with Rockstar International to develop, produce and design all internationalized versions of the game sites.
                     <ul>
                            <li><a href="http://www.rockstargames.com/maxpayne3/IT" target="_blank">Italian</a></li>
                            <li><a href="http://www.rockstargames.com/maxpayne3/DE" target="_blank">Deutch</a></li>
                            <li><a href="http://www.maxpayne3-eljuego.com" target="_blank">Espana</a></li>
                            <li><a href="http://www.maxpayne3-lejeu.com" target="_blank">Francias</a></li>
                        </ul>
                    
                    </li>
                    <li>Kept all internationalized sites synced with their US counterpart through use of .htaccess, Apache, cakePHP, HTML and CSS.</li>
                </ul>                        
                <div class="clr"></div>
                    <br>
            </section>
        </div><!-- End #mp3 -->                        
        <div class="hide">
            <section class="block" id="rdr">
                <h1 class="resume-title left">Web Developer/Designer</h1>
                 <p class="resume-location right">New York, NY</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.rockstargames.com" target="_blank"><img height="66" width="150" alt="Rockstargames Red Dead Redemption Logo" src="/img/logo_rdr.jpg"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Worked on the marketing campaigns of Red Dead Redemption.</li>
                    <li>Coordinated with Rockstar International to develop, produce and design all internationalized versions of the game sites.</li>
                    <li>Kept all internationalized sites synced with their US counterpart through use of .htaccess, Apache, cakePHP, HTML and CSS.
                        <ul>
                            <li><a href="http://www.rockstargames.com/reddeadredemption/IT" target="_blank">Italian</a></li>
                            <li><a href="http://www.rockstargames.com/reddeadredemption/DE" target="_blank">Deutch</a></li>
                            <li><a href="http://www.reddeadredemption-eljuego.com" target="_blank">Espana</a></li>
                            <li><a href="http://www.reddeadredemption-lejeu.com" target="_blank">Francias</a></li>
                        </ul>
                    
                    </li>
                    <li>Set up the Research department with a comprehensive way of sending out e-blasts, archiving sent e-blasts, and developed new research sites as needed.</li>
                </ul>                        
                <div class="clr"></div>
                    <br>
            </section>
        </div><!-- End #rdr -->                        
        <div class="hide">
            <section class="block" id="mcla">
                <h1 class="resume-title left">Web Developer/Designer</h1>
                 <p class="resume-location right">New York, NY</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.rockstargames.com" target="_blank"><img height="44" width="150" alt="Rockstargames Midnight Club Los Angeles Logo" src="/img/logo_mcla.jpg"></a>
                    <a href="http://www.rockstargames.com" target="_blank"><img height="47" width="150" alt="Rockstargames Midnight Club Los Angeles South Central Logo" src="/img/logo_mclasc.jpg"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Worked on the marketing campaigns of Midnight Club Los Angeles and Midnight Club Los Angeles: South Central .</li>
                    <li>Designed, developed and deployed the Rockstar Propaganda e-newsletter via Lyris List Manager, using HTML.</li>
                </ul>                        
                <div class="clr"></div>
                    <br>
            </section>
        </div><!-- End #mcla -->                        
        <div class="hide">
            <section class="block" id="ctw">
                <h1 class="resume-title left">Web Developer/Designer</h1>
                 <p class="resume-location right">New York, NY</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.rockstargames.com" target="_blank"><img height="147" width="150" alt="Rockstargames Chinatown Wars Logo" src="/img/logo_ctw.jpg"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Worked on the marketing campaigns of Chinatown Wars.</li>
                    <li>Coordinated with Rockstar International to develop, produce and design all internationalized versions of the game sites:
                        <ul>
                            <li><a href="http://www.rockstargames.com/chinatownwars/IT" target="_blank">Italian</a></li>
                            <li><a href="http://www.rockstargames.com/chinatownwars/DE" target="_blank">Deutch</a></li>
                            <li><a href="http://www.chinatownwars-eljuego.com" target="_blank">Espana</a></li>
                            <li><a href="http://www.chinatownwars-lejeu.com" target="_blank">Francias</a></li>
                        </ul>
                    </li>
                    <li>Kept all internationalized sites synced with their US counterpart through use of .htaccess, Apache, cakePHP, HTML and CSS.</li>
                    <li>Designed, developed and deployed the Rockstar Propaganda e-newsletter via Lyris List Manager, using HTML.</li>
                </ul>                        
                <div class="clr"></div>
                    <br>
            </section>
        </div><!-- End #ctw -->                        
        <div class="hide">
            <section class="block" id="tbogt">
                <h1 class="resume-title left">Web Developer/Designer</h1>
                 <p class="resume-location right">New York, NY</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.rockstargames.com" target="_blank"><img height="137" width="150" alt="Rockstargames The Ballas of Gay Tony Logo" src="/img/logo_tbogt.jpg"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Worked on the marketing campaigns of Grand Theft Auto The Ballad of Gay Tony.</li>
                    <li>Coordinated with Rockstar International to develop, produce and design all internationalized versions of the game sites.
                     <ul>
                            <li><a href="http://www.rockstargames.com/theballadofgaytony/IT" target="_blank">Italian</a></li>
                            <li><a href="http://www.rockstargames.com/theballadofgaytony/DE" target="_blank">Deutch</a></li>
                            <li><a href="http://www.theballadofgaytony-eljuego.com" target="_blank">Espana</a></li>
                            <li><a href="http://www.theballadofgaytony-lejeu.com" target="_blank">Francias</a></li>
                        </ul>
                    </li>
                    <li>Kept all internationalized sites synced with their US counterpart through use of .htaccess, Apache, cakePHP, HTML and CSS.</li>
                    <li>Designed, developed and deployed the Rockstar Propaganda e-newsletter via Lyris List Manager, using HTML.</li>
                </ul>                        
                <div class="clr"></div>
                    <br>
            </section>
        </div><!-- End #tbogt -->                        
        <div class="hide">
            <section class="block" id="tlad">
                <h1 class="resume-title left">Web Developer/Designer</h1>
                 <p class="resume-location right">New York, NY</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.rockstargames.com" target="_blank"><img height="140" width="150" alt="Rockstargames The Lost and Damned Logo" src="/img/logo_tlad.jpg"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Worked on the marketing campaigns of the recently released Chinatown Wars, Episodes from Liberty City, Beaterator, Midnight Club Los Angeles, Grand Theft Auto IV, Grand Theft Auto Chinatown Wars, Bully Scholarship, Max Payne 3 and Red Dead Redemption.</li>
                    <li>Coordinated with Rockstar International to develop, produce and design all internationalized versions of the game sites.
                     <ul>
                            <li><a href="http://www.rockstargames.com/thelostanddamned/IT" target="_blank">Italian</a></li>
                            <li><a href="http://www.rockstargames.com/thelostanddamned/DE" target="_blank">Deutch</a></li>
                            <li><a href="http://www.thelostanddamned-eljuego.com" target="_blank">Espana</a></li>
                            <li><a href="http://www.thelostanddamned-lejeu.com" target="_blank">Francias</a></li>
                        </ul>
                    
                    </li>
                    <li>Kept all internationalized sites synced with their US counterpart through use of .htaccess, Apache, cakePHP, HTML and CSS.</li>
                    <li>Designed, developed and deployed the Rockstar Propaganda e-newsletter via Lyris List Manager, using HTML.</li>
                </ul>                        
                <div class="clr"></div>
                    <br>
            </section>
        </div><!-- End #tlad -->                        
        <div class="hide">
            <section class="block" id="liz">
                <h1 class="resume-title left">Web Developer/Designer </h1>
                 <p class="resume-location right">Los Angeles, CA</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.liz-osborn.com" target="_blank"><img height="41" width="130" alt="Liz Osborn Logo" src="/img/logo_lizosborn.png"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Utilizing jQuery, PHP, XML and Flash, I was able to give an aspiring actress a more prominent presence on the web.</li>
                    <li>Gave prospective clients the ability to contact her by putting in a jQuery e-mail form validation using regex.</li>
                </ul>
                <div class="clr"></div>
                <br>
            </section>
        </div><!-- END #liz -->
        <div class="hide">
            <section class="block" id="blindsight">
                <h1 class="resume-title left">Web Developer/Designer </h1>
                 <p class="resume-location right">London, UK</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.blindsightthemovie.com" target="_blank"><img height="205" width="130" alt="Blindsight Logo" src="/img/logo_blindsight.jpg"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Worked remotely to continuously update and maintain the site with the latest media and news content.</li>
                    <li>Coordinated the move of the website and DNS settings to a new hosting service.</li>
                    <li>Created working files of website graphics using .jpgs from server in order to implement the requested visual updates.</li>
                    <li>Made the website W3C and 508 compliant to ensure usability for the vision and hearing impaired.</li>
                </ul>                        
                <div class="clr"></div>
                <br>
            </section>
        </div><!-- END #blindsight -->
        <div class="hide">
            <section class="block" id="communikids">
                <h1 class="resume-title left">Interactive Designer </h1>
                 <p class="resume-location right">Chantilly, VA</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.communikids.com" target="_blank"><img height="49" width="150" alt="Communikids Logo" src="/img/logo_communikids.jpg"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Designed a flash intro for a Washington D.C. based school focusing on helping children develop their secondary language skills to be come bilingual.</li>
                    <li>Participated in the creation of the language based flash games, designing the color by number and memory game.</li>
                </ul>                        
                <div class="clr"></div>
                <br>
            </section>
        </div><!-- END #communikids -->
        <div class="hide">
            <section class="block" id="approvalove">
                <h1 class="resume-title left">Interactive Designer </h1>
                 <p class="resume-location right">Chantilly, VA</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.iloveagoodaudit.com" target="_blank"><img height="31" width="150" alt="Blindsight Logo" src="/img/logo_approva.jpg"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Designed a microsite for to connect with a segment of the audit industry that is usually forgotten about. </li>
                    <li>Storyboarded and designed a series of e-cards using Flash.</li>
                    <li>Made various micro sites using <a href="http://www.iloveagoodaudit.com" target="_blank">ILoveAGoodAudit.com</a> as the landing page</li>
                </ul>                        
                <div class="clr"></div>
                <br>
            </section>
        </div><!-- END #approvalove -->
        <div class="hide">
            <section class="block" id="audittrail">
                <h1 class="resume-title left">Interactive Designer </h1>
                 <p class="resume-location right">Chantilly, VA</p>
                <div class="clr"></div>
            	<aside class="resume-logo left">
                    <a href="http://www.approva.com/audittrail" target="_blank"><img height="31" width="150" alt="Blindsight Logo" src="/img/logo_approva.jpg"></a>
                </aside>
                <ul class="resume-list right">
                    <li>Designed a blog for an auditing company to open a line of communication with the audit industry that is usually forgotten about. </li>
                    <li>Wire framed the look and feel of the site.</li>
                    <li>Designed a set of icons that were used to indicate different sections.</li>
                </ul>                        
                <div class="clr"></div>
                <br>
            </section>
        </div><!-- END #audittrail -->
        <div class="hide">
            <section class="block" id="biography">
                <p class="resume-list">During his tenure at the University of Maryland, Elan took many courses in art, ranging from<br/>drawing to welding to steel metal sculpture. It was not until he enrolled in a computer-aided<br/>design course that he was able to unify his passion for the arts and his irresistible desire to<br/>work with computers. By uniting the two, Elan was able to find a<br/>harmony that he used as a basis to pursue his career.
                </p>
                <br/>
                <br/>
                <p class="resume-list">
Graduating from the University of Maryland with a bachelors degree in fine art and a<br/>concentration in graphic design, Elan's classical art training, coupled with his passion<br/>for interactive design, have proven a perfect marriage. His innate ability to create original,<br/>innovative designs proves an asset to any project in which he is involved. With skills ranging<br/>from traditional sculpture and stained glass to Flash animation and 3D digital modeling, few<br/>rival Elan's diverse skill set in both art and interactive realms. In addition to his<br/>experience in the commercial industry, Elan developed and instructed classes at the<br/>University of Maryland's acclaimed Art and Learning Center for several years. 
                </p>
            </section>
        </div><!-- END #biography -->
